name: Clojure CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: clojure:temurin-11-alpine
    services:
      dynamo-db:
        image: amazon/dynamodb-local
        ports:
          - 8000/tcp
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: clj -X:test
      env:
        DYNAMO_HOST: dynamo-db

    - name: Run Build
      run: clj -X:build jar
