name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: clojure:temurin-11-bullseye-slim
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: clj -X:test
