name: Clojure CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: clojure:temurin-11-bullseye
    services:
      dynamo-db:
        image: amazon/dynamodb-local
        ports:
          - 8000/tcp
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.2
      with:
        cli: 1.11.1.1208              # Clojure CLI based on tools.deps
    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        # List all files containing dependencies:
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-
    - name: Run tests
      run: clj -X:test
#       env:
#         DYNAMO_HOST: dynamo-db

    - name: Run Build
      run: clj -X:build jar
